// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import NextAuthSessionProvider from "../../providers/NextAuthSessionProvider";
// import ToastProvider from "../../providers/ToastProvider";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Todo App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <NextAuthSessionProvider>
//           <ToastProvider />
//             {children}
//         </NextAuthSessionProvider>
//       </body>
//     </html>
//   );
// }


import Head from 'next/head';
import { Inter } from 'next/font/google';
import NextAuthSessionProvider from '../../providers/NextAuthSessionProvider';
import ToastProvider from '../../providers/ToastProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Head>
          <title>Todo App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <NextAuthSessionProvider>
          <ToastProvider />
          {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
