import type { Metadata } from "next";
import { Stint_Ultra_Condensed, IBM_Plex_Mono } from "next/font/google";
import NextAuthSessionProvider from "../../providers/NextAuthSessionProvider";
import ToastProvider from "../../providers/ToastProvider";
import "./globals.css";

const stintUltraCondensed = Stint_Ultra_Condensed({ subsets: ["latin"], weight: "400" });
const ibmPlexMono = IBM_Plex_Mono({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${stintUltraCondensed.className} ${ibmPlexMono.className}`}>
        <NextAuthSessionProvider>
          <ToastProvider />
          {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
